{"uid":"e9c6cd79112d89fd","name":"An uncaught error was detected outside of a test","fullName":"An uncaught error was detected outside of a test","historyId":"c59643030e1e776644fd5d1d6aa79cfc","time":{"start":1706768571279,"stop":1706768571478,"duration":199},"status":"failed","statusMessage":"The following error originated from your test code, not from Cypress.\n\n  > cy.allure.writeEnvironmentInfo is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","statusTrace":"TypeError: The following error originated from your test code, not from Cypress.\n\n  > cy.allure.writeEnvironmentInfo is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n    at ./cypress/support/e2e.js (webpack:///./cypress/support/e2e.js:20:10)\n    at __webpack_require__ (webpack:///webpack/bootstrap:19:0)\n    at 0 (http://localhost:37185/__cypress/tests?p=cypress/support/e2e.js:13777:18)\n    at __webpack_require__ (webpack:///webpack/bootstrap:19:0)\n    at eval (webpack:///webpack/bootstrap:83:0)\n    at eval (http://localhost:37185/__cypress/tests?p=cypress/support/e2e.js:87:10)\n    at eval (<anonymous>)","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"failed","statusMessage":"The following error originated from your test code, not from Cypress.\n\n  > cy.allure.writeEnvironmentInfo is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","statusTrace":"TypeError: The following error originated from your test code, not from Cypress.\n\n  > cy.allure.writeEnvironmentInfo is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n    at ./cypress/support/e2e.js (webpack:///./cypress/support/e2e.js:20:10)\n    at __webpack_require__ (webpack:///webpack/bootstrap:19:0)\n    at 0 (http://localhost:37185/__cypress/tests?p=cypress/support/e2e.js:13777:18)\n    at __webpack_require__ (webpack:///webpack/bootstrap:19:0)\n    at eval (webpack:///webpack/bootstrap:83:0)\n    at eval (http://localhost:37185/__cypress/tests?p=cypress/support/e2e.js:87:10)\n    at eval (<anonymous>)","steps":[],"attachments":[{"uid":"e38902aa59822d92","name":"cypress/e2e/spec.cy.js:2024-02-01T06:22:51.322Z","source":"e38902aa59822d92.png","type":"image/png","size":38026},{"uid":"943cb7154c3a23f7","name":"video recording","source":"943cb7154c3a23f7.mp4","type":"video/mp4","size":69758}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":2,"hasContent":true,"attachmentStep":false},"afterStages":[],"labels":[{"name":"package","value":"cypress.e2e.spec.cy.js"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":[]},"source":"e9c6cd79112d89fd.json","parameterValues":[]}